# 開発用の設定
spring.datasource.url=jdbc:postgresql://db:5432/dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

