# 開発用の設定
spring.datasource.url=jdbc:postgresql://db:5432/dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# --- 全自動反映のための設定 ---

# 【フロントエンド用】
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false

# 【バックエンド用】
spring.devtools.restart.enabled=true
# HTMLやCSSの変更ではアプリを再起動させない（画面リロードだけでOKにする）
spring.devtools.restart.exclude=static/**,templates/**
